### PR TITLE
upgrade version

### PR DESCRIPTION
**Pull request by abu-2022**
the server version and the agent version need to be upgraded to versions 9.2.0 and 8.13.0, respectively.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Sorry. We don't have ppl maintaing this repo anymore.

**Comment by abu-2022** [comment]
Sorry. May I ask why you chose not to support these two message queues?

**Comment by wu-sheng** [comment]
If someone felt interested, it could be done.

**Comment by abu-2022** [comment]
OK, thank you

**Pull request closed without merging**
