### PR TITLE
Add the guide documents of the pulsar plugin and fix the bug of loading pulsar configurations

### PR DESCRIPTION
**Pull request by codeglzhang**
The guide doc has been added. When I wrote the guide, I found that the data types of some configuration [items](https://pulsar.apache.org/docs/en/2.8.0/client-libraries-java/#consumer) are objects, such as `DeadLetterPolicy`, `Set`. The previous implementation of the configuration parsing does not support parsing in this case, so I modified the corresponding code to fix it.

### CODE REVIEW

**Comment by codeglzhang** [comment]
@wu-sheng the guide docs has been added.

**Review by wu-sheng — COMMENTED** [review]
Documents look good. You should add 2 links into root readme.md to these 2 separate files.

Another thing I noticed, the root `<groupId>org.openskywalking</groupId>` is wrong, please change `openskwaylking` to `skyapm`. I think we missed this when changed package name in the last time.

**Comment by wu-sheng** [comment]
@codeglzhang I also have invited you as a member of `/SkyAPM/teams/transporter-sig/`. Then you could review, update, merge PR from other contributors. I think this Summer 2021 journey has proved you are qualified enough.

**Comment by wu-sheng** [comment]
Also, recommend you to raise a PR to update 2 documents in the ASF repos
1. Add a new section at the end of Kafka fetcher, https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/kafka-fetcher.md, linking to your Pulsar fetcher.
2. Add another option at the end of Java reporter doc, https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/advanced-reporters.md, linking to your Pulsar reporter.

___

About you mentioned 8.7.0-based, I want to check with you and @dmsolr . I think this reporter and fetcher are working well with latest 8.8.1 and 8.9.0 release as well, right? We didn't add any new channels, even we will(in the future), this plugins still work just missing some parts of data.

I would recommend to add 8.8.1 to e2e testing, and use GHA Matrix to make further new version adding easier. What do you think?

**Comment by codeglzhang** [comment]
> About you mentioned 8.7.0-based, I want to check with you and @dmsolr . I think this reporter and fetcher are working well with latest 8.8.1 and 8.9.0 release as well, right? We didn't add any new channels, even we will(in the future), this plugins still work just missing some parts of data.

For supporting the 8.8.1 release, a little code needs to modify. Because in the 8.8.1, the `init()` method in `IConsumer.java` is changed.  `IConsumer` is implemented by some classes in the Reporter.
In the 8.7.0 the `init()` is defined as follows.
```
public interface IConsumer<T> {
    void init();
...
}
```
But in the 8.8.1 the `init()` is defined as follows.
```
public interface IConsumer<T> {
    void init(final Properties properties);
...
}
```
The reason why we choose 8.7.0-based is that at the time of development, the release version of skywalking agent Java is still 8.7.0.  Transporter plugins relies on some of its components, such as `agent-analyzer`, `apm-agent-core`, and `apm-util`.

**Comment by wu-sheng** [comment]
I see. Thanks for explanation. Let's add version to the root readme.

```markdown
## Available Transporter Plugins
* Pulsar Transporter(SkyWalking OAP server and Java agent 8.7.0)
  * OAP Fetcher
  * Java agent reporter
```

**Comment by dmsolr** [comment]
@codeglzhang We replace the version with `0.1.0`. And then we move on to support sw 8.8.0+ since `0.2.0`. 
If something has to be fixed,  we release a bug-fixed version such as `0.1.1`.
HDYT, @codeglzhang @wu-sheng

**Comment by wu-sheng** [comment]
> @codeglzhang We replace the version with `0.1.0`. And then we move on to support sw 8.8.0+ since `0.2.0`. If something has to be fixed, we release a bug-fixed version such as `0.1.1`. HDYT, @codeglzhang @wu-sheng

`0.1.0` or `1.0.0` both work for me. We just need to make milestone and pom version matched.

**Comment by codeglzhang** [comment]
>Documents look good. You should add 2 links into root readme.md to these 2 separate files.
>the root <groupId>org.openskywalking</groupId> is wrong, please change openskwaylking to skyapm. I think we missed this when changed package name in the last time.

I have fixed it. In addition, I corrected the version to 0.1.0.

**Comment by codeglzhang** [comment]
> @codeglzhang I also have invited you as a member of /SkyAPM/teams/transporter-sig/. Then you could review, update, merge PR from other contributors. I think this Summer 2021 journey has proved you are qualified enough.
Thanks. I feel honored.

**Review by wu-sheng — APPROVED** [review]
Wait for your mentor's @dmsolr confirmation.

**Comment by wu-sheng** [comment]
> > @codeglzhang I also have invited you as a member of /SkyAPM/teams/transporter-sig/. Then you could review, update, merge PR from other contributors. I think this Summer 2021 journey has proved you are qualified enough.
> > Thanks. I feel honored.

You need to accept through the link in the mail(GitHub registration mail) or at this page, https://github.com/orgs/SkyAPM/teams

**Review by dmsolr — APPROVED** [review]
LGTM

**Pull request merged**
